defmodule ExAST.CommentQueryTest do
  use ExUnit.Case, async: true

  import ExAST.Query

  alias ExAST.Patcher

  test "comment matches leading and inside comments by substring" do
    source = """
    # public API
    def with_leading do
      :ok
    end

    def with_inside do
      # TODO: clean up
      :ok
    end
    """

    matches = Patcher.find_all(source, from("def name do ... end") |> where(comment("TODO")))
    assert Enum.map(matches, & &1.captures[:name]) == [{:with_inside, nil, nil}]

    matches =
      Patcher.find_all(source, from("def name do ... end") |> where(comment_before("public API")))

    assert Enum.map(matches, & &1.captures[:name]) == [{:with_leading, nil, nil}]
  end

  test "comment_inside accepts regex" do
    source = """
    def run do
      # FIXME later
      :ok
    end
    """

    assert [_] =
             Patcher.find_all(
               source,
               from("def run do ... end") |> where(comment_inside(~r/TODO|FIXME/))
             )
  end

  test "comment_inline matches same-line comments" do
    source = """
    def run do
      value = 1 # temporary
      other = 2
    end
    """

    query = from("value = 1") |> where(comment_inline("temporary"))
    assert [_] = Patcher.find_all(source, query)

    query = from("other = 2") |> where(comment_inline("temporary"))
    assert [] = Patcher.find_all(source, query)
  end

  test "comment_after matches immediately following comments" do
    source = """
    def run do
      :ok
    end
    # after run

    def other do
      :ok
    end
    """

    query = from("def run do ... end") |> where(comment_after("after run"))
    assert [_] = Patcher.find_all(source, query)
  end

  test "comment text matchers support case-insensitive text prefix suffix and exact" do
    source = """
    # Generated by tool
    def generated do
      value = 1 # TEMPORARY
      :ok
    end
    """

    assert [_] =
             Patcher.find_all(
               source,
               from("def generated do ... end")
               |> where(comment_before(prefix("generated", case: false)))
             )

    assert [_] =
             Patcher.find_all(
               source,
               from("value = 1") |> where(comment_inline(text("temporary", case: false)))
             )

    assert [_] =
             Patcher.find_all(
               source,
               from("def generated do ... end") |> where(comment_before(suffix("tool")))
             )

    assert [_] =
             Patcher.find_all(
               source,
               from("def generated do ... end")
               |> where(comment_before(exact("Generated by tool")))
             )
  end

  test "comment predicates require source input" do
    ast =
      Sourceror.parse_string!("""
      # TODO
      def run do
        :ok
      end
      """)

    assert [] = Patcher.find_all(ast, from("def run do ... end") |> where(comment("TODO")))
  end
end
